version: "3.8"

services:
  # web:
  #   build: .
  #   command: uvicorn app.main:app --reload --workers 1 --host 0.0.0.0 --port 8000
  #   volumes:
  #     - .:/usr/src/app
  #   ports:
  #     - 8004:8000
  #   environment:
  #     - DATABASE_URL=postgresql+asyncpg://postgres:postgres@db:5432/foo
  #   depends_on:
  #     - db

  db:
    image: postgres:15.3
    ports:
      - 5436:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=foo
